<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Nombres*</label>
              <input type="text" name="nombres" id="txt_nombres" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Ape Paterno*</label>
              <input type="text" name="ape_paterno" id="txt_ape_paterno" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Ape Materno*</label>
              <input type="text" name="ape_materno" id="txt_ape_materno" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Sexo*</label>
            <select class="form-control" id="slct_sexo" name="sexo">
                <option value="">Seleccione</option>
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
            </select>
        </div>
    </div>
</div>