<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Nombre*</label>
              <input type="text" name="nombre" id="txt_nombre" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Codigo*</label>
              <input type="text" name="codigo" id="txt_codigo" required class="form-control">
        </div>
    </div>
</div>