<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Nombre*</label>
              <input type="text" name="nombre" id="txt_nombre" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Apellido*</label>
              <input type="text" name="apellido" id="txt_apellido" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Edad*</label>
              <input type="text" name="edad" id="txt_edad" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Sexo*</label>
            <select class="form-control" id="slct_sexo" name="sexo">
                <option value="">Seleccione</option>
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
            </select>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Salario*</label>
              <input type="text" name="salario" id="txt_salario" required class="form-control">
        </div>
    </div>
</div>