<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>producto*</label>
              <input type="text" name="nombreproducto" id="txt_nombreproducto" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>tipo*</label>
              <input type="text" name="tipo" id="txt_tipo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>descripcion*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
</div>