<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Carrera*</label>
              <input type="text" name="carrera" id="txt_carrera" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Grado*</label>
              <input type="text" name="grado" id="txt_grado" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Universidad*</label>
              <input type="text" name="universidad" id="txt_universidad" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Año Egreso*</label>
            <select class="form-control" id="slct_anio_egreso" name="anio_egreso">
                <option value="">Seleccione</option>
                <option value="2020">2020</option>
                <option value="2019">2019</option>
                <option value="2018">2018</option>
                <option value="2017">2017</option>
                <option value="2016">2016</option>
                <option value="2015">2015</option>
                <option value="2014">2014</option>
                <option value="2013">2013</option>
                <option value="2012">2012</option>
                <option value="2011">2011</option>
                <option value="2010">2010</option>
                <option value="2009">2009</option>
                <option value="2008">2008</option>
                <option value="2007">2007</option>
                <option value="2006">2006</option>

            </select>
        </div>
    </div>
</div>