<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Tipo*</label>
              <input type="text" name="tipo" id="txt_tipo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Descripcion*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
</div>