<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Nombres*</label>
              <input type="text" name="nombres" id="txt_nombres" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Apellidos*</label>
              <input type="text" name="apellidos" id="txt_apellidos" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Usuario*</label>
              <input type="text" name="usuario" id="txt_usuario" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Estado*</label>
            <select class="form-control" id="slct_estado" name="estado">
                <option value="">Seleccione</option>
                <option value="Activo">Activo</option>
                <option value="Inactivo">Inactivo</option>
            </select>
        </div>
    </div>
</div>