<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="fontawesome/css/all.min.css">
<link rel="stylesheet" type="text/css" href="css/sweetalert2.min.css">
<!-- DataTable CSS -->
<link rel="stylesheet" type="text/css" href="css/datatable/dataTables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/datatable/fixedHeader.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/datatable/responsive.bootstrap.min.css">
<style type="text/css">
	body{
		background-color: #9dd1ea;
	}
	.container{
		//background-color: #fff;
	}
	.content-table{
		background-color: #fff;
	    margin: 20px 0px;
	    padding: 20px;
	    border-radius: 15px;
	}
</style>